### ISSUE TITLE
Using with "current" dump

### ISSUE THREAD

**Issue by DataJunkie** [whym/wikihadoop#7] opened 2011-10-28 20:12 UTC
Is it possible to use WikiHadoop with the XML dump containing only the current version of the pages (no revisions)?

**Comment by drdee** [comment] 2011-10-28 22:45
I think you can, you should specify  the number of revision to be 1 but I am not sure if Wikihadoop is useful for this usecase. Wikihadoop is developed to create the diffs between revisions.

**Comment by whym** [comment] 2011-10-28 23:13
Diederik is right.  If you add the option -Dorg.wikimedia.wikihadoop.previousRevision=true, WikiHadoop writes one revision at a time to the mapper.  Please note that you would need to write a new mapper (or modify the revision differ) for your own purpose.

**Comment by DataJunkie** [comment] 2011-10-30 17:58
Thanks! I plan to write my own mapper.

**Comment by whym** [comment] 2011-10-31 02:27
Sorry, a small correction. As you may see, -Dorg.wikimedia.wikihadoop.previousRevision=**false** should do the work, not 'true'.

**Comment by DataJunkie** [comment] 2011-10-31 02:55
Thanks for the correction.
The good news is that I got the job to start running without errors.

One thing I am confused about. If I use only one dump file in bz2 format, won't that only spawn one mapper, and essentially defeat the purpose of using MapReduce? How could I divide the the XML dump file such that each file is valid XML and namespaces and metadata don't get scrapped?

**Comment by whym** [comment] 2011-10-31 03:06
That is basically what we provide (or at least we try to provide) and you don't need to divide the dump file by yourself.  You can control how you split the input file with -Dmapreduce.input.fileinputformat.split.minsize=BYTES.  Given a big bz2 file, WikiHadoop will split it into chunks with the sizes as close to this value as possible.

**Comment by drdee** [comment] 2011-10-31 14:05
Yes, that is the added file of wikihadoop: it will use multiple mappers for a single file.

**Comment by DataJunkie** [comment] 2011-10-31 21:03
When I run the job on a dump, I seem to only be getting one map task. Am I supposed to set the number of mappers for the job? Also, this one map task seems to be get killed after two hours with a "Error: GC overhead limit exceeded." Is there something obvious I am missing?

**Comment by drdee** [comment] 2011-10-31 21:05
Can you paste your full command line and give some details on your hardware? How much memory etc etc
Best
Diederik

**Comment by DataJunkie** [comment] 2011-10-31 21:22
Thanks. This is the command line I am using:

hadoop jar /home/ryan/Documents/wikihadoop/wikihadoop-0.1.jar \
  -Dorg.wikimedia.wikihadoop.excludePagesWith="<title>(Media|Special|Talk|User|User talk|Wikipedia|Wikipedia talk|File|File talk|MediaWiki|MediaWiki talk|Template|Template talk|Help|Help talk|Category|Category   talk|Portal|Portal talk|Book|Book talk):" \
  -Dmapreduce.input.fileinputformat.split.minsize=500000000 \
  -Dorg.wikimedia.wikihadoop.previousRevision=true \
  -Dmapreduce.task.timeout=8000000 \
  -input /user/ryan/enwiki-latest.xml.bz2 \
  -output /user/ryan/out \
  -inputformat org.wikimedia.wikihadoop.StreamWikiDumpInputFormat \
  -jobconf mapred.map.tasks=8 

This system is a dual Xeon E5645 (12 cores total, hyperthreaded so 24 threads), 24GB RAM, approximately 20GB free.

**Comment by drdee** [comment] 2011-11-01 19:36
What happens when you run the command exactly as explained on https://github.com/whym/wikihadoop/wiki? and you might want to give more memory to the jvm

**Comment by Fkawala** [comment] 2012-04-10 12:55
Hello, 
I have the same issue, having the blocksize parameter set at a given value X, triggers the splitting of the file if I use a non compressed dump, while it doesn't when I use the same file compressed as a Bzip2. 

Any hints to solve this issue ? It would be greatly appreciated.

François.

**Comment by drdee** [comment] 2012-04-15 13:37
We are looking into it, i'll let you know once I know more.
Best,
Diederik

**Comment by whym** [comment] 2012-04-28 12:08
I couldn't reproduce the problem when I gave one input file with this command (note that I used the new version with some minor changes in the command line parameters):

/usr/lib/hadoop-beta/bin/hadoop jar /usr/lib/hadoop-beta/mapred/contrib/streaming/hadoop-0.21.0-streaming.jar -libjars wikihadoop-0.2.jar -D mapred.child.upperlimit=31243 -D mapred.task.timeout=0 -D mapreduce.input.fileinputformat.split.minsize=20000000 -D mapred.reduce.tasks=0 -D mapred.output.compress=true -input /tmp/simplewiktionary-20120424-pages-meta-history.xml -output /tmp/output

Could you share the exact url to the file you (both DataJunkie and Fkawala) used?
I used http://dumps.wikimedia.org/simplewiktionary/20120424/simplewiktionary-20120424-pages-meta-history.xml.bz2 this time.

**Comment by Fkawala** [comment] 2012-04-28 13:58
Hello, 

The file I've used is the one available at : http://dumps.wikimedia.org/frwiki/20120312/frwiki-20120312-pages-articles.xml.bz2

I'll retry to process this file with exactly the parameters that you've used, and try to gather more information about this issue.

**Comment by Fkawala** [comment] 2012-04-28 14:55
I've tried to process the wikidump with your command line. It ends as previously with one mapper only. 
What could I do to help you further ?

**Comment by whym** [comment] 2012-04-30 14:45
I tried with the frwiki dump with essentially the same command line and got 135 map tasks.

Could you give me the execution log of the job you tried with the uncompressed xml? Use https://gist.github.com/ if it's too long.

This time the command line I used was:

/usr/lib/hadoop-beta/bin/hadoop jar /usr/lib/hadoop-beta/mapred/contrib/streaming/hadoop-0.21.0-streaming.jar -libjars wikihadoop-0.2.jar -D mapred.child.upperlimit=31243 -D mapred.task.timeout=0 -D mapreduce.input.fileinputformat.split.minsize=20000000 -D mapred.reduce.tasks=0 -D mapred.output.compress=true -input /tmp/frwiki-20120312-pages-articles.xml -output /tmp/output-frwiki2

**Comment by Fkawala** [comment] 2012-05-01 08:57
I'll have to re-run the job, which isn't possible today. However, a first thing to know is that I've used Dumbo upon hadoop streaming. Knowing that do you think that the logs could be useful ?

**Comment by whym** [comment] 2012-05-01 09:51
Fkawala: To be clear, I was referring to the log files written by Hadoop, not the console log.  I was guessing that the problem was caused by some unexpected configuration in your installation of Hadoop.  To identify it, I'd start by looking for warnings in the logs.

Assuming that you (or Dumbo) didn't customize how the log is written by Hadoop, a relevant log file should be found at somewhere like this: ${HADOOP_HOME}/logs/userlogs/job_201204281120_0003/attempt_201204281120_0003_m_000057_0/.

**Comment by whym** [comment] 2015-09-27 03:45
Closing for the original issue. Other issues are welcome to be reported with procedures to reproduce.

**Closed as completed by whym** 2015-09-27 03:45 UTC
